### ISSUE TITLE
JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by rzajac** [rabbitmq/discussions#122]
When I do

`rabbitmqadmin get queue=my_queue ackmode=ack_requeue_true count=4`

I get error:

```Traceback (most recent call last):
  File "./bin/rabbitmqadmin", line 1193, in <module>
    main()
  File "./bin/rabbitmqadmin", line 532, in main
    method()
  File "./bin/rabbitmqadmin", line 697, in invoke_get
    result = self.post(uri, json.dumps(upload))
  File "./bin/rabbitmqadmin", line 567, in post
    return self.http("POST", "%s/api%s" % (self.options.path_prefix, path), body)
  File "./bin/rabbitmqadmin", line 635, in http
    die(json.loads(resp.read())['reason'])
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'```

My management plugin version: v3.8.5 rabitmq version  3.6.15

All messages in the queue are JSON stroings. I tried to set `encoding` parameter to string or auto but it does not help. What should I do to get the message?

**Comment by rzajac** [comment]
@michaelklishin The problem was mismatched versions of management plugin and rabbitmq. Thank you for pointing me in right direction.

**Comment by michaelklishin** [comment]
I don't think RabbitMQ 3.8.x can even start with a plugin from 3.6.x, and vice versa. Modern versions include a supported core version series field. My guess is that you mean `rabbitmqadmin` mismatch? In any case, thank you for reporting back!
