### ISSUE TITLE
Block processing messages when receiving a low-level error

### ISSUE THREAD

**Issue by DVMaslov** [rabbitmq/discussions#27]
RabbitMQ 3.6.12, Erlang 20.3
amqp-client: 5.7.3

When I consume a broken message from a queue I get an error: "com.rabbitmq.client.MalformedFrameException: Unrecognised type in table". The processing of this situation is the break of the connection. The message is then returned back to the queue. Now there is no way to configure the behavior, throw this message in dead letter exchange or just throw it out of the queue. This blocks further message processing until we manually delete the broken message.

**Comment by acogoluegnes** [comment]
You're using a version of RabbitMQ [which is not longer supported](https://www.rabbitmq.com/versions.html). Please upgrade.

If you manage to reproduce on a maintained version of the broker, please provide the procedure to make debugging easier. Thanks.

**Comment by michaelklishin** [comment]
Also relevant here: [Poison message handling](https://www.rabbitmq.com/quorum-queues.html#feature-comparison) in 3.8 and [Message TTL](https://www.rabbitmq.com/ttl.html).

**Comment by DVMaslov** [comment]
Quorum Queues is not suitable for our usage scenario.
I do not think that any version of rabbitmq can guarantee the absence of broken messages.
It seems more correct to reject messages in amqp-client when throw MalformedFrameException.

**Comment by acogoluegnes** [comment]
@DVMaslov Can you provide a way to reproduce? I understand this is an awkward situation, it'd be useful to understand how such a malformed message ended up in the broker in the first place (bug in a client library?) and how the Java client could handle this in an appropriate manner.

**Comment by DVMaslov** [comment]
We were unable to reproduce the problem.
We have a cluster of 3 nodes. During the appearance of broken messages, we had problems with DNS. Maybe it's related.
The reason for the appearance of broken messages is most likely the broker itself. Since the broken messages were old duplicates (sent and successfully processed 10-16 hours ago).

We will update rabbitMQ and maybe it will help to avoid similar problems in the future.
But even outside the context of the current problem, I think the current handling of the MalformedFrameException error in amqp-client is not correct. I think in this case, you should reject the message or even better give the ability to configure the behavior.

**Comment by acogoluegnes** [comment]
This is a fair point, it's just you're the first to report this error in the last few years, so some steps to reproduce would have avoided spending too much time on something that does not seem to affect many people.

Do you have at least a stacktrace?

**Comment by 130133362948a** [comment]
![DFE4FF1B-1C5C-447D-A2C3-4001F09278B8](https://user-images.githubusercontent.com/57547028/70492591-d6708300-1afc-11ea-94cc-7a0721799368.png)

**Comment by DVMaslov** [comment]
stacktrace:
`com.rabbitmq.client.MalformedFrameException: Unrecognised type in table
	at com.rabbitmq.client.impl.ValueReader.readFieldValue(ValueReader.java:207)
	at com.rabbitmq.client.impl.ValueReader.readTable(ValueReader.java:149)
	at com.rabbitmq.client.impl.ValueReader.readTable(ValueReader.java:232)
	at com.rabbitmq.client.impl.ContentHeaderPropertyReader.readTable(ContentHeaderPropertyReader.java:108)
	at com.rabbitmq.client.AMQP$BasicProperties.<init>(AMQP.java:1716)
	at com.rabbitmq.client.impl.AMQImpl.readContentHeaderFrom(AMQImpl.java:4845)
	at com.rabbitmq.client.impl.CommandAssembler.consumeHeaderFrame(CommandAssembler.java:101)
	at com.rabbitmq.client.impl.CommandAssembler.handleFrame(CommandAssembler.java:158)
	at com.rabbitmq.client.impl.AMQCommand.handleFrame(AMQCommand.java:89)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:112)
	at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:672)
	at com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:48)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:599)
	at java.base/java.lang.Thread.run(Thread.java:834)`
