### ISSUE TITLE
Producer can not generated over 740

### ISSUE THREAD

**Issue by siranohyuk** [rabbitmq/discussions#41]
my version is 2.10.0.RC1

my running options here
`./runjava com.rabbitmq.perf.PerfTest --producers 1000 --publishing-interval 1 --producer-scheduler-threads 10 --size 1500 --use-millis`

and result
`id: test-111855-657, starting producer #740
Main thread caught exception: java.util.concurrent.TimeoutException
11:20:16.319 [main] ERROR com.rabbitmq.perf.PerfTest - Main thread caught exception
java.util.concurrent.TimeoutException: null
	at com.rabbitmq.utility.BlockingCell.get(BlockingCell.java:77)
	at com.rabbitmq.utility.BlockingCell.uninterruptibleGet(BlockingCell.java:120)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:502)
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:325)
	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:64)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:156)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1110)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1067)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:965)
	at com.rabbitmq.perf.MulticastSet$ConnectionCreator.createConnection(MulticastSet.java:730)
	at com.rabbitmq.perf.MulticastSet.createConnection(MulticastSet.java:267)
	at com.rabbitmq.perf.MulticastSet.createProducers(MulticastSet.java:324)
	at com.rabbitmq.perf.MulticastSet.run(MulticastSet.java:173)
	at com.rabbitmq.perf.PerfTest.main(PerfTest.java:325)
	at com.rabbitmq.perf.PerfTest.main(PerfTest.java:445)`

**Comment by siranohyuk** [comment]
thanks but as you know, number of max threads and number of max connections in java get affected 
my linux setting's open file limit and max user processes large enough
what should I look for?

```
ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 62811
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65536
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 62811
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```


```
ulimit -aH
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 62811
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65536
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 62811
```

**Comment by lukebakken** [comment]
Both of these may be too low -

```
open files                      (-n) 65536
max user processes              (-u) 62811
```

**Comment by lukebakken** [comment]
For what it's worth, this is what I see on my FreeBSD 12 workstation when starting with the same arguments:

```
id: test-074117-622, starting producer #735, channel #0
id: test-074117-622, starting producer #736
id: test-074117-622, starting producer #736, channel #0
id: test-074117-622, starting producer #737
[WARNING] 
java.lang.OutOfMemoryError: unable to create new native thread
    at java.lang.Thread.start0 (Native Method)
    at java.lang.Thread.start (Thread.java:717)
    at com.rabbitmq.client.impl.AMQConnection.startMainLoop (AMQConnection.java:485)
    at com.rabbitmq.client.impl.SocketFrameHandler.initialize (SocketFrameHandler.java:178)
    at com.rabbitmq.client.impl.AMQConnection.start (AMQConnection.java:319)
```

```
$ ulimit -a
number of pseudoterminals            (-P) unlimited
socket buffer size       (bytes, -b) unlimited
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) 33554432
file size               (blocks, -f) unlimited
max kqueues                     (-k) unlimited
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 938790
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 524288
cpu time               (seconds, -t) unlimited
max user processes              (-u) 34189
virtual memory          (kbytes, -v) unlimited
swap size               (kbytes, -w) unlimited
```

**Comment by michaelklishin** [comment]
Default limits on Linux are known to be inadequate for servers, e.g. the open file handles one is 1024.

**Comment by siranohyuk** [comment]
ok so I know that single node RabbitMQ server how many simultaneously producers send message without delay

**Comment by acogoluegnes** [comment]
The first exception:

```
Main thread caught exception: java.util.concurrent.TimeoutException
11:20:16.319 [main] ERROR com.rabbitmq.perf.PerfTest - Main thread caught exception
java.util.concurrent.TimeoutException: null
	at com.rabbitmq.utility.BlockingCell.get(BlockingCell.java:77)
	at com.rabbitmq.utility.BlockingCell.uninterruptibleGet(BlockingCell.java:120)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:502)
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:325)
	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:64)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:156)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1110)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1067)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:965)
	at com.rabbitmq.perf.MulticastSet$ConnectionCreator.createConnection(MulticastSet.java:730)
	at com.rabbitmq.perf.MulticastSet.createConnection(MulticastSet.java:267)
	at com.rabbitmq.perf.MulticastSet.createProducers(MulticastSet.java:324)
	at com.rabbitmq.perf.MulticastSet.run(MulticastSet.java:173)
	at com.rabbitmq.perf.PerfTest.main(PerfTest.java:325)
	at com.rabbitmq.perf.PerfTest.main(PerfTest.java:445)
```

does not seem to be related to resources on the client side, but because the server does not respond fast enough to open a lot of connections. This could also be because there's no enough threads to dispatch RPC responses (so problem on the client side here).

Whatever reason it is, try to use [NIO](https://rabbitmq.github.io/rabbitmq-perf-test/stable/htmlsingle/#workloads-with-a-large-number-of-clients) for PerfTest with the `--nio-threads` option, this would limit the number of threads used by connections. Limit also the number of threads for heartbeat with `--heartbeat-sender-threads`. Not related to threads, you can also start the publishers within a ramp-up period to avoid them publishing at the same time (`--producer-random-start-delay` option). The command would become:

```
./runjava com.rabbitmq.perf.PerfTest --producers 1000 --publishing-interval 1  --size 1500 --use-millis \
  --producer-random-start-delay 1800 \
  --producer-scheduler-threads 10 \
  --nio-threads 50 \
  --heartbeat-sender-threads 10
```

Play around with the last 3 options to find the appropriate compromise for your test and the available resources for PerfTest.

**Comment by siranohyuk** [comment]
@acogoluegnes  I tried your option but result is here when i was not use your option, always stop at #740 and now always stop #821

```
id: test-112256-804, starting producer #821
Main thread caught exception: java.util.concurrent.TimeoutException
11:24:24.574 [main] ERROR com.rabbitmq.perf.PerfTest - Main thread caught exception
java.util.concurrent.TimeoutException: null
	at com.rabbitmq.utility.BlockingCell.get(BlockingCell.java:77)
	at com.rabbitmq.utility.BlockingCell.uninterruptibleGet(BlockingCell.java:120)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:502)
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:325)
	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:64)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:156)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1110)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1067)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:965)
	at com.rabbitmq.perf.MulticastSet$ConnectionCreator.createConnection(MulticastSet.java:730)
	at com.rabbitmq.perf.MulticastSet.createConnection(MulticastSet.java:267)
	at com.rabbitmq.perf.MulticastSet.createProducers(MulticastSet.java:324)
	at com.rabbitmq.perf.MulticastSet.run(MulticastSet.java:173)
	at com.rabbitmq.perf.PerfTest.main(PerfTest.java:325)
	at com.rabbitmq.perf.PerfTest.main(PerfTest.java:445)
```

**Comment by acogoluegnes** [comment]
I reproduced on a system with a small file limit (1024):

```
ulimit -a
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-m: resident set size (kbytes)      unlimited
-u: processes                       62774
-n: file descriptors                1024
-l: locked-in-memory size (kbytes)  16384
-v: address space (kbytes)          unlimited
-x: file locks                      unlimited
-i: pending signals                 62774
-q: bytes in POSIX msg queues       819200
-e: max nice                        0
-r: max rt priority                 0
-N 15:                              unlimited
```

I increased the soft limit for the current terminal session:

```
ulimit -n 3084
```

and started the broker in the same terminal. You can confirm the setting is taken into account from the node details page in the management UI or with `rabbitmqctl status`.

![image](https://user-images.githubusercontent.com/514737/71880561-e8ac0400-3130-11ea-95cf-68ad7dfea21b.png)

PerfTest then manages to create all the producers. So it seems it's a problem on the server side not on the client side. You need to configure the file descriptors limit appropriately on the server side. See [the link](https://www.rabbitmq.com/networking.html#open-file-handle-limit) @michaelklishin provided above, the solution I used is just a workaround to experiment with as the setting is just for the current terminal session and the hard limit remains low for a production server (4096 in this case).

**Comment by siranohyuk** [comment]
my open file limit soft 65546 and hard 200000 I think almost maximum

and I checked `rabbitmqctl status`

```
rabbitmqctl status
Status of node rabbit@s01 ...
[{pid,29191},
 {running_applications,
     [{rabbitmq_management,"RabbitMQ Management Console","3.3.5"},
      {rabbitmq_web_dispatch,"RabbitMQ Web Dispatcher","3.3.5"},
      {webmachine,"webmachine","1.10.3-rmq3.3.5-gite9359c7"},
      {mochiweb,"MochiMedia Web Server","2.7.0-rmq3.3.5-git680dba8"},
      {rabbitmq_mqtt,"RabbitMQ MQTT Adapter","3.3.5"},
      {rabbitmq_management_agent,"RabbitMQ Management Agent","3.3.5"},
      {rabbit,"RabbitMQ","3.3.5"},
      {os_mon,"CPO  CXC 138 46","2.2.14"},
      {inets,"INETS  CXC 138 49","5.9.8"},
      {mnesia,"MNESIA  CXC 138 12","4.11"},
      {amqp_client,"RabbitMQ AMQP Client","3.3.5"},
      {xmerl,"XML parser","1.3.6"},
      {sasl,"SASL  CXC 138 11","2.3.4"},
      {stdlib,"ERTS  CXC 138 10","1.19.4"},
      {kernel,"ERTS  CXC 138 10","2.16.4"}]},
 {os,{unix,linux}},
 {erlang_version,
     "Erlang R16B03-1 (erts-5.10.4) [source] [64-bit] [smp:4:4] [async-threads:30] [hipe] [kernel-poll:true]\n"},
 {memory,
     [{total,43681128},
      {connection_procs,436224},
      {queue_procs,61704},
      {plugins,465560},
      {other_proc,14310392},
      {mnesia,89984},
      {mgmt_db,168984},
      {msg_index,25688},
      {other_ets,1108536},
      {binary,1865272},
      {code,19863754},
      {atom,703377},
      {other_system,4581653}]},
 {alarms,[]},
 {listeners,[{clustering,25672,"::"},{amqp,5672,"::"},{mqtt,1883,"::"}]},
 {vm_memory_high_watermark,0.4},
 {vm_memory_limit,6595267788},
 {disk_free_limit,50000000},
 {disk_free,235217117184},
 {file_descriptors,
     [{total_limit,924},{total_used,10},{sockets_limit,829},{sockets_used,6}]},
 {processes,[{limit,1048576},{used,272}]},
 {run_queue,0},
 {uptime,59}]
...done.
```

**Comment by acogoluegnes** [comment]
I see the following in the `rabbitmqctl status` output:

```
{file_descriptors,
     [{total_limit,924},{total_used,10},{sockets_limit,829},{sockets_used,6}]},
```

The setting is not taken into account for some reason, this is why PerfTest cannot create 1000 connections, because the server reaches its sockets limit before.

**Comment by siranohyuk** [comment]
@acogoluegnes That's right I ran that command and found out why it's not growing. 
Then how I increase server limit setting?

**Comment by acogoluegnes** [comment]
This is documented [here](https://www.rabbitmq.com/networking.html#open-file-handle-limit). Please follow the links given, the setting depends on the operating system.

**Comment by michaelklishin** [comment]
While not really related, RabbitMQ 3.3 has gone out of support [in 2015](https://www.rabbitmq.com/versions.html). Please [upgrade](https://www.rabbitmq.com/upgrade.html).

**Comment by siranohyuk** [comment]
problem solved! reference from [here](https://ro-che.info/articles/2017-03-26-increase-open-files-limit) thanks

**Comment by acogoluegnes** [comment]
Glad to hear. Thanks for reporting back.
