### ISSUE TITLE
TLS support on Android 5.1

### ISSUE THREAD

**Issue by mattfiocca** [rabbitmq/discussions#42]
* RabbitMQ version = 3.7.7
* Erlang version = 20.2.2
* Client library version = `implementation 'com.rabbitmq:amqp-client:4.11.3'`

I am trying to use this client library on Android 5.1 and getting an `java.lang.NoSuchMethodError` when Android API level is less than 24. Here's the stack trace:

```
Fatal Exception: java.lang.NoSuchMethodError: No virtual method setEndpointIdentificationAlgorithm(Ljava/lang/String;)V in class Ljavax/net/ssl/SSLParameters; or its super classes (declaration of 'javax.net.ssl.SSLParameters' appears in /system/framework/core-libart.jar)
	at com.rabbitmq.client.SocketConfigurators.enableHostnameVerification(SocketConfigurators.java:72)
	at com.rabbitmq.client.SocketConfigurators$2.configure(SocketConfigurators.java:60)
	at com.rabbitmq.client.SocketConfigurators$AbstractSocketConfigurator$1.configure(SocketConfigurators.java:135)
	at com.rabbitmq.client.impl.SocketFrameHandlerFactory.create(SocketFrameHandlerFactory.java:56)
	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:61)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:177)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1161)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1118)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1076)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1236)
	at com.incidentclear.driver.lib.networking.Rabbit.connect(Rabbit.java:163)
	at com.incidentclear.driver.lib.services.DataService.tick(DataService.java:322)
	at com.incidentclear.driver.lib.services.DataService.access$500(DataService.java:53)
	at com.incidentclear.driver.lib.services.DataService$2.run(DataService.java:212)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

Looks like `SSLParameters#setEndpointIdentificationAlgorithm` isn't available to android 5.1 devices, which you've got on line of `58` of `/src/main/java/com/rabbitmq/client/SocketConfigurators.java`:
```java
sslParameters.setEndpointIdentificationAlgorithm("HTTPS");
           // ^ issue here
```

Here is my connection factory:
```java
ConnectionFactory connFactory = new ConnectionFactory();
connFactory.setHost(host);
connFactory.setPort(port);
connFactory.setUsername(user);
connFactory.setPassword(pass);
connFactory.setVirtualHost("/");
connFactory.enableHostnameVerification(); // <-- exception thrown here
connFactory.useSslProtocol();
connFactory.setAutomaticRecoveryEnabled(true);
connFactory.setNetworkRecoveryInterval(5000); // retry every 5s
```

I was able to temporarily suppress the exception with:
```java
...
if ( Build.VERSION.SDK_INT >= Build.VERSION_CODES.N ) {
	connFactory.enableHostnameVerification();
}
...
```

But i just wanted to bring this to your attention. I was looking for any documentation concerning android compatibility without any luck. Maybe i'm just blind.

Anyway, perhaps some API level documentation for android could be added or workarounds developed?

I should add that I am setting a default SSLContext in other parts of my app for other SSL related things:
```java
String protocol = "TLSv1.2";
SSLContext ctx = SSLContext.getDefault();
String sslProtocol = ctx.getProtocol();
if ( !sslProtocol.equalsIgnoreCase(protocol) ) {
	ctx = SSLContext.getInstance(protocol);
	ctx.init(null, null, null);
	SSLContext.setDefault(ctx);
}
```

Would that affect rabbit's connection initialization?

**Comment by michaelklishin** [comment]
There are only two Android-specific aspects:

 * [Only Android 7+ is supported](https://www.rabbitmq.com/api-guide.html#versions) by the newest releases of this client since it uses Java 8 features. `4.x` versions of this client still support Java 6 but it will be discontinued at some point
 * On Android, network activity on the main thread is prohibited

I'm afraid we won't be modifying the client to support Android `5.x`. It was released in June 2014 and last updated in April 2015. You are welcome to maintain a fork.

If there is an easy enough way to make the client compatible with that version without sacrificing the peer verification features our Java client tries to enable, we'd consider a pull request against the `4.x` branch of this client. Otherwise, Android `5.x` support is not a priority for our team.

**Comment by michaelklishin** [comment]
So Spring seems to [be dropping JDK 6 support](https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Versions) this month. This means there are very few reasons to continue maintaining RabbitMQ Java client's `4.x` branch. If a version if out of extended by support by JDK vendors and Spring, it really is dead.

**Comment by mattfiocca** [comment]
Fair enough, thanks for the reply!

Our app is enterprise in nature and ultimately we are trying to roll legacy devices out of our fleets. This issue goes away with replaced hardware.

**Comment by acogoluegnes** [comment]
@mattfiocca You can use `ConnectionFactory#enableHostnameVerification(HostnameVerifier)` to enable hostname verification with a custom `HostnameVerifier` instance. Apache HttpComponents Client provides an implementation which AFAIK is compatible with Java 6 and should hopefully works with the Android version you're using.
