### ISSUE TITLE
ACCESS_REFUSED for a remote connection

### ISSUE THREAD

**Issue by srburton** [rabbitmq/discussions#89]
I have a recent problem, I'm running rabbitmq in a container on ECS on AWS.

I have a vpn, when my application on localhost accesses the rabbitmq server works normally like the image below.

![vpn-connection](https://user-images.githubusercontent.com/15394508/78951573-fdd65d00-7aa8-11ea-883f-bb1a7d202c54.png)

When the service is on AWS I have the following errors:

![ecs-docker](https://user-images.githubusercontent.com/15394508/78951578-0169e400-7aa9-11ea-9b93-9dc5bd196a1e.png)

````
RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable ---> RabbitMQ.Client.Exceptions.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.
   at RabbitMQ.Client.Framing.Impl.Connection.StartAndTune()
   at RabbitMQ.Client.Framing.Impl.Connection.Open(Boolean insist)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IFrameHandler fh)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   at App.Infra.Integration.RabbitMq.Factories.PersistentConnection.<TryConnect>b__14_2() in /src/src/Infra/Integration/App.Infra.Integration.RabbitMq/Factories/PersistentConnection.cs:line 76
   at Polly.Policy.<>c__DisplayClass108_0.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Policy.<>c__DisplayClass138_0.<Implementation>b__0(Context ctx, CancellationToken token)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
````

**Comment by srburton** [comment]
@michaelklishin  Thanks, I'll take a look at this loopback question, but it was already a big help :-)
