### ISSUE TITLE
Channel exception: NOT_FOUND - no queue 'LO_TO_XFC_LOGISTICS_ACK_QUEUE' in vhost '/'

### ISSUE THREAD

**Issue by ZShUn** [rabbitmq/discussions#90]
There is this exception when the project starts, but it can consume data normally, what is the matter?

specific exception:

Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method(reply-code=404, reply-text=NOT_FOUND - no queue 'ACK_QUEUE' in vhost '/', class-id=50, method-id=20)
	at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:504)
	at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:346)
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:178)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:111)
	at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:643)
	at com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:47)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:581)
	... 1 more

**Comment by ZShUn** [comment]
It can be confirmed that the application does not actively create a queue
